name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

# Required for GCP auth
permissions:
  contents: read
  id-token: write

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: gcp-auth
        name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/381573879100/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-oidc-provider
          service_account: github@foundation-349518.iam.gserviceaccount.com
      - uses: ./
      - run: |
          if [[ "${secretKey}" != "secret value" ]]; then
            echo "Secret not decoded properly"
            exit 1
          fi
          echo key is "$secretKey"
